@include("forms.parts.name", ["value"=>$inputs["name"]??"","church"=>$church,"number"=>$number])
@include("forms.parts.ic", ["value"=>$inputs["ic"]??"","church"=>$church,"number"=>$number])
@include("forms.parts.age", ["value"=>$inputs["age"]??"","church"=>$church,"number"=>$number])
@include("forms.parts.involvement", ["value"=>$inputs["involvement"]??"","church"=>$church,"number"=>$number, "category"=>"Chapel"])
@include("forms.parts.gender", ["value"=>$inputs["gender"]??"","church"=>$church,"number"=>$number])
@include("forms.parts.differently_abled", ["value"=>$inputs["differently_abled"]??"","church"=>$church,"number"=>$number])
@include("forms.parts.leadership", ["value"=>$inputs["leadership"]??"","church"=>$church,"number"=>$number])
@include("forms.parts.accomodation", ["value"=>$inputs["accomodation"]??"","church"=>$church,"number"=>$number])
@include("forms.parts.diet", ["value"=>$inputs["diet"]??"","church"=>$church,"number"=>$number])
@include("forms.parts.allergy", ["value"=>$inputs["allergy"]??"","church"=>$church,"number"=>$number])
@include("forms.parts.email", ["value"=>$inputs["email"]??"","church"=>$church,"number"=>$number])
@include("forms.parts.mobile", ["value"=>$inputs["mobile"]??"","church"=>$church,"number"=>$number])